export default [
  {
    files: ["**/*.js"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: {
        Audio: "readonly",
        cancelAnimationFrame: "readonly",
        caches: "readonly",
        document: "readonly",
        fetch: "readonly",
        HTMLElement: "readonly",
        navigator: "readonly",
        performance: "readonly",
        Promise: "readonly",
        self: "readonly",
        requestAnimationFrame: "readonly",
        URL: "readonly",
        window: "readonly",
      },
    },
    rules: {
      "array-callback-return": "error",
      "block-scoped-var": "error",
      curly: ["error", "all"],
      eqeqeq: ["error", "always"],
      "no-alert": "error",
      "no-console": "warn",
      "no-constant-condition": "error",
      "no-debugger": "error",
      "no-duplicate-imports": "error",
      "no-else-return": "error",
      "no-empty": ["error", { allowEmptyCatch: true }],
      "no-implicit-globals": "error",
      "no-multi-assign": "error",
      "no-param-reassign": "error",
      "no-return-assign": "error",
      "no-shadow": "warn",
      "no-template-curly-in-string": "error",
      "no-unneeded-ternary": "error",
      "no-unused-vars": ["error", { argsIgnorePattern: "^_" }],
      "no-use-before-define": ["error", { functions: false }],
      "object-shorthand": ["error", "always"],
      "prefer-const": "error",
      "prefer-template": "error",
    },
  },
];
